/**
 * Loads NG_APP_* values from .env files and writes
 * src/environments/environment.values.ts (gitignored).
 *
 * Priority (later wins), matching common dotenv conventions:
 *   .env → .env.local → .env.{mode} → .env.{mode}.local → process.env
 *
 * Usage: node scripts/sync-env.mjs [development|local|production]
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const mode = process.argv[2] || process.env.NG_APP_ENV || 'development';

const REQUIRED_KEYS = [
  'NG_APP_SUPABASE_URL',
  'NG_APP_SUPABASE_KEY',
  'NG_APP_API_URL',
  'NG_APP_AUTH_TOKEN',
];

function parseEnvFile(filePath) {
  if (!existsSync(filePath)) {
    return {};
  }

  const values = {};
  const text = readFileSync(filePath, 'utf8');

  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) {
      continue;
    }

    const eq = line.indexOf('=');
    if (eq <= 0) {
      continue;
    }

    const key = line.slice(0, eq).trim();
    let value = line.slice(eq + 1).trim();

    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }

    values[key] = value;
  }

  return values;
}

function loadEnv(modeName) {
  const files = [
    '.env',
    '.env.local',
    `.env.${modeName}`,
    `.env.${modeName}.local`,
  ];

  const merged = {};
  for (const file of files) {
    Object.assign(merged, parseEnvFile(join(root, file)));
  }

  // Existing process env wins (CI / Netlify / local overrides).
  for (const key of REQUIRED_KEYS) {
    if (process.env[key] !== undefined && process.env[key] !== '') {
      merged[key] = process.env[key];
    }
  }

  return merged;
}

const env = loadEnv(mode);
const missing = REQUIRED_KEYS.filter((key) => !env[key]);

if (missing.length > 0) {
  console.error(
    `[sync-env] Missing required variables for mode "${mode}":\n  - ${missing.join('\n  - ')}\n` +
      `Copy .env.example to .env.${mode} (and fill values), or set them in the environment.`
  );
  process.exit(1);
}

const outPath = join(root, 'src', 'environments', 'environment.values.ts');
const contents = `/**
 * AUTO-GENERATED by scripts/sync-env.mjs - do not edit or commit.
 * Mode: ${mode}
 */
export const envValues = {
  supabaseUrl: ${JSON.stringify(env.NG_APP_SUPABASE_URL)},
  supabaseKey: ${JSON.stringify(env.NG_APP_SUPABASE_KEY)},
  apiUrl: ${JSON.stringify(env.NG_APP_API_URL)},
  authToken: ${JSON.stringify(env.NG_APP_AUTH_TOKEN)},
} as const;
`;

writeFileSync(outPath, contents, 'utf8');
console.log(`[sync-env] Wrote ${outPath} (mode=${mode})`);
